### ISSUE TITLE
 hook `trailing-whitepsce` with an extra argument --autofix

### ISSUE THREAD

**Issue by drjasonharrison** [ngoet/pre-commit-demo#1]
I saw that your .pre-commit-config.yaml has a use of the hook `trailing-whitepsce` with an extra argument:

```
  - id: trailing-whitespace
  - args:
    - --autofix
 ```
Unfortunately the `- args` and `- --autofix` lines are incorrect yaml. 

However, the pre-commit code for trailing-whitespace does not have an argument `--autofix` https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/trailing_whitespace_fixer.py

Are you trying to use a different repo or hook definition?

**Comment by ngoet** [comment]
Hi @drjasonharrison, thank you for pointing out - you're absolutely right. I have updated the yaml file. 

I have recently switched to ruff for linting, which is a lot faster, so I'd recommend taking a look at this too if you're interested in using pre-commit hooks/linters: https://docs.astral.sh/ruff/
